### ISSUE TITLE
The online demo has some wrong about login module

### ISSUE THREAD

**Issue by okpay88** [ralscha/webauthn-demo#2]
### when i test the login.  print some error for:
> Uncaught (in promise): NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

>  Uncaught (in promise): InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable

### the auth start json payload:
```
{
    "assertionId": "7mxfRrIl3C/RMEYfmoCK1w==", 
    "publicKeyCredentialRequestOptions": {
        "challenge": "G5WndtPVoUTBAnthf5Retk302pHCvXRwuzS8YVvxeCo", 
        "rpId": "demo.rasc.ch", 
        "allowCredentials": [ ], 
        "userVerification": "preferred", 
        "extensions": { }
    }
}
```

**Comment by ralscha** [comment]
Looks like a client issue. What browser do you use?
