### ISSUE TITLE
How to set up the demo locally?

### ISSUE THREAD

**Issue by chiaaifen** [ralscha/webauthn-demo#3]
Hi I'm new to Webauthn and came across your repo. I have been trying to set up a Webauthn demo, and will like to ask how do I go about setting up the demo on localhost with your codes? Thank you!

**Comment by ralscha** [comment]
Hi

It looks like access with `localhost` no longer works. But you can still run it on your local computer with `ngrok`

Prerequisites: Java, Node.Js, MariaDb 

1. Start ngrok: `ngrok http -host-header=rewrite 8100`
2. Update application.properties (see https://golb.hplar.ch/2019/08/webauthn.html#testing)
3. Start server: `cd server && ./mvnw spring-boot:run`
4. Start client: `cd client && ng serve --disable-host-check=true --port=8100`
5. Open ngrok https URL in a browser

**Comment by chiaaifen** [comment]
okay thank you so much for the prompt response! i will go and try it out

**Comment by konstantinabasta** [comment]
Hello!! I followed your instructions but I have the following issue when trying to test it locally (with ngrok configured). The popup for entering the fingerprint is not visible. It appears only the choice with the usb key. BUT when I tried the registration on your demo it was successful. Both fingerprint, pin and usb key was visible.

**Comment by ralscha** [comment]
Not sure what the problem is. I only have a yubikey. I just tested it in my local development environment and it works. 
Does the usb key login work locally and only the option for the fingerprint is missing?

**Comment by RodriMora** [comment]
> Hello!! I followed your instructions but I have the following issue when trying to test it locally (with ngrok configured). The popup for entering the fingerprint is not visible. It appears only the choice with the usb key. BUT when I tried the registration on your demo it was successful. Both fingerprint, pin and usb key was visible.

i think you might be missing: npm install @github/webauthn-json
