### ISSUE TITLE
Cannot build the project

### ISSUE THREAD

**Issue by rodrigo-bejar** [ralscha/webauthn-demo#5]
npm install runs ok

**ionic serve** or **ionic cap build android** throws the following errors:

Cannot find module '@github/webauthn-json/dist/types/basic/json' or its corresponding type declarations
6 import {PublicKeyCredentialRequestOptionsJSON} from '@github/webauthn-json/dist/types/basic/json';

Cannot find module '@github/webauthn-json/src/webauthn-json/basic/json' or its corresponding type declarations
 8 import { PublicKeyCredentialCreationOptionsJSON } from '@github/webauthn-json/src/webauthn-json/basic/json';  
 
*@github/webauthn-json/dist/types/basic/json* exists under node_modules but is not visible for some reason
*@github/webauthn-json/src/webauthn-json/basic/json* doesn't exists under node_modules
 
 I'm running the project with VSCode and node 20.13.1

**Comment by ralscha** [comment]
Hi
I tested this just 3 days ago and `npm install && ionic serve -o` works fine on my Windows 11 computer. 

Here is my setup:
- Windows 11
- Node 20.14.0
- npm 10.8.1
- ionic 7.2.0

Do you run it on Linux or macOS?

**Comment by rodrigo-bejar** [comment]
I have Win11 also.

But I realized that is types issue. I changed these missing types to **any** and removed the imports causing the errors.

It's only to running locally so it's not a big offense. =D

Thank you for your attention! =)
